language: node_js

git:
  submodules: false

cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.cache"

before_install:
  - git submodule update --init --remote --recursive

install:
  - yarn --silent

script:
  - yarn run lint

before_deploy:
  - pip install --user awscli
  - yarn run clean
  - yarn run build

deploy:
  provider: script
  script: yarn run deploy
  cleanup: false
  edge: true
  on:
    tags: true

# after_deploy:
#   - aws configure set preview.cloudfront true
#   - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

env:
  global:
    - secure: cz0WtgtwXhUQPdSoNFX43lj5/duBrqDDLOBAL7p0cCI7G2sKksR4YsUW1SoGVCr3WHckESTeoJ5QX3mbcIIffk+jBd/8e4xZ36W9dxfh/bKIR2AGClWQ04iz0RbHqO8yaPupNn3laSgJYhI4G7XEhUT2zLSCzvqTvZrqR/AkVmM8mUe+PEDOejz7em1lFLXSlOmWRoLnIB+EutfhoAYbc+u3WjIJRPWK4n8F0+vA868LptVwtpUKx5IQ7NgXWrRM215a6ckEolhU/TycqEFdcVuiVoWl5TEBmU/xBF5BBwO4G3QgHcIS0qTu2dxy6XnWgoYmsdC+ve0c3VpXxsj0vd0girzuRiWKTSlqmuo5OUU96578FvxNGmbuSzq1GX7Xh+XfddpTWrXEB2kHhLRHI8Jd6P0IUcAnE4Aqu5BUBaN+1CF1XqglsNgW9lRKuRJAK8TiUB9QUIwm3LtXtxTYj4domYRGkhRYZ3EGy6j1fx1SL5rsXhw4qz2nq8TaVU4yMxWZHhHalc+bONnl9EImYwatpcJoz+8IWEYbQdmxAIuQ+g12nJuc2ICouGxn4TODxy5mdeopxdGS5g5WlU9u4qr4/JnAaix8rN4Gy29KpPwciODBKOQ/zlUgV4ULdfNNwLJ5Kb/AMdJNLq74KO6jbFOaYe9QJjNMYHBp8BRSTW0=
