language: node_js

git:
  submodules: false

cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.cache"

before_install:
  - git submodule update --init --remote --recursive

install:
  - yarn --silent

script:
  - yarn run lint

before_deploy:
  - pip install --user awscli
  - yarn run clean
  - yarn run build

deploy:
  provider: script
  script: yarn run deploy
  cleanup: false
  edge: true
  on:
    tags: true

# after_deploy:
#   - aws configure set preview.cloudfront true
#   - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

env:
  global:
    - secure: 3fAPbQlawootm+xXpb0ak9aW1f6NhtuYgGp2OAqLSoL9Rl/0nyxCTi5cYROyy/SWFaxg2v40bEugICZRn+TkaC2K76+PLijboctkWcn48Mn38AalChz1rMSyCL+KHnPj+3gLuWxBXYtKSk3B16CVLK4GslwF5uUu4LZEQBAKch1yaOLzDPyu2C5J7YG4FWCJ6G/6b5lGwaQeYLbgmSRkaWGb9M8qP/rcJRbTLPcxG27WtHaoRSBRr8Kc1gvmIaHsqGHg0fLBEG/WrDUYXeslV/PzTU/jcOrHYgpEeiRY8AsMXKG2ghTJQLPaFSexhyv1AohCWseD2+VUQiTIltpZEESZ4Cb5+vxRopWP0O3wZq/FgP/rNbcp7hcOad4VU9xkaxmLBWqC1ONgsL6nk+qwtuHLs+I7skG3GeBqv7erFx2/liCgYd1VfP3qISJLbloOlPHN//HXESPZrQKBs7TsAejm9EXjDRuwYHn+k6AKxycmXBv9hiFDTfaXM0oZj8FZB1LcV48ZItdk6vfPA88oTKYEU9OKkLJq6plhpm1dkJgIZiMxHUqz1wDdzrBkdWV1cgQgOKUhTImbVAoPTN6qcMLwOnseIbfA4hP0TUfWXOjkaAt01Dp0xjMfapaKsD5qVKpEuyAf7xIKTu5CrcyuK6aWPdNvwsskmUiJ3fEIvZE=
    - secure: wyHMi2x7oqP2ulThY5YPc7HT/nsMlhZJADu9HAYZ82OZKXigB7pjhTfTSCnpUcOkkae7r9pgQFTk9xHp5l0fMPf9KiskcS3ZbkNMhwbJBUddiqJQxsLcHcdwH+Wu64r5LF83epKwKlabI9Hsg2mz6UNtCXWWUA4mkB+atCddF3Iz9IVm0jx50FPLDu5Qr0QSnHhq/R6p70I+zj1BhopS9x3ZbfxZUOY9Mt1I6EiQh4rPW8JYkBws54Eam39FymfJgucZiZHrbamw4AwjrwI7AtEd4EREqO/vF2nPn1Gh1QSZaiM8eyNEqgy9E+s7DZ5Ea9wis3HHmXBLq0dA48hx/BtHf/UfyfRe7eUKzDeJXtR7h3O0Y9NWUGMsyLrZiET3f9Xqd+oj96/itoPYu2wdDSJSNEjMt3LHgoL41yOvrEq4He9mOfWEvsUvzVKVPzlSWdxbs0eTaKsDnz5Qg0axCEsRufVAhK+rCXKcejvgLmyl1cLKxhWbdjmXi9SsiGlPr8zdjlznCOO9UtYr3TdvkFX/wrcavaC5iFcuHICr7NjaqNWGHfX3CHqhvBn1/2hg/1KZ4Nf2NoX+a1laoCrPV6pU3zSCy53mmU+1Nx5g4hLj7t/W8nC0wEENdISOwjLCuBFYwDwrKlRIZA95l2bP7pEDOOUcyxeSZWk9UOPDHzg=
